version: "3.2"

volumes:
  web_data:
    external: true

services:
  web:
    container_name: app
    build:
      context: ./
      dockerfile: devserver.Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on: 
      - postgres
    env_file:
        ./dev.env
    networks:
      - elk


  postgres:
    container_name: postgres_1
    image: kartoza/postgis:12.1
    ports:
      - "5400:5432"
    volumes:
      - web_data:/var/lib/postgresql:rx
    env_file:
      ./dev.env
    networks:
      - elk

networks:
  elk:
    driver: bridge
   